# Generated by Django 5.1 on 2024-09-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen Principal')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen Secundaria 1')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen Secundaria 2')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen Secundaria 3')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('section', models.CharField(choices=[('que_es_la_reehm', '¿Qué es la Reehm?'), ('protocolo', 'Protocolo'), ('encuentros', 'Encuentros'), ('reseñas', 'Reseñas'), ('agenda', 'Agenda')], default='principal', max_length=50, verbose_name='Sección')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug (puedes dejarlo en blanco y se genera sólo)')),
                ('date_published', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('carrusel', models.BooleanField(default=False, verbose_name='Principal en Carrusel')),
                ('importante', models.BooleanField(default=False, verbose_name='Principal en Importante')),
                ('otras', models.BooleanField(default=False, verbose_name='Principal en Otras')),
            ],
        ),
    ]
