# Generated by Django 5.1 on 2024-09-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='revistas/imagenes/', verbose_name='Imagen de la Revista')),
                ('archivo_pdf', models.FileField(upload_to='revistas/pdfs/', verbose_name='Archivo PDF')),
            ],
        ),
    ]
